// ── Mock data for all screens ─────────────────────────────────────────────────

export const MOCK_SYSTEMS = [
  {
    ci_id: 'SYS-001',
    system_name: 'LIMS Core',
    system_type: 'Laboratory Information Management',
    custodian: 'Dr. Sarah Mitchell',
    owner: 'James Thornton',
    rag_status: 'green',
    readiness_score: 8.7,
    open_gaps: 2,
    last_evaluated: '2026-04-28T14:32:00Z',
    validation_status: 'Validated',
  },
  {
    ci_id: 'SYS-002',
    system_name: 'ELN Platform',
    system_type: 'Electronic Lab Notebook',
    custodian: 'Priya Sharma',
    owner: 'Michael O\'Brien',
    rag_status: 'amber',
    readiness_score: 6.1,
    open_gaps: 7,
    last_evaluated: '2026-04-27T09:15:00Z',
    validation_status: 'Validated',
  },
  {
    ci_id: 'SYS-003',
    system_name: 'MES Gateway',
    system_type: 'Manufacturing Execution System',
    custodian: 'Thomas Riedel',
    owner: 'Angela Brooks',
    rag_status: 'red',
    readiness_score: 4.2,
    open_gaps: 14,
    last_evaluated: '2026-04-26T11:45:00Z',
    validation_status: 'Revalidation Required',
  },
  {
    ci_id: 'SYS-004',
    system_name: 'QMS Suite',
    system_type: 'Quality Management System',
    custodian: 'Linda Park',
    owner: 'Robert Chen',
    rag_status: 'green',
    readiness_score: 9.1,
    open_gaps: 1,
    last_evaluated: '2026-04-28T16:00:00Z',
    validation_status: 'Validated',
  },
  {
    ci_id: 'SYS-005',
    system_name: 'Chromatography DS',
    system_type: 'Data Acquisition System',
    custodian: 'Elena Vasquez',
    owner: 'David Kim',
    rag_status: 'amber',
    readiness_score: 5.8,
    open_gaps: 9,
    last_evaluated: '2026-04-25T08:30:00Z',
    validation_status: 'Validated',
  },
  {
    ci_id: 'SYS-006',
    system_name: 'Regulatory Submissions',
    system_type: 'Document Management',
    custodian: 'Mark Jensen',
    owner: 'Susan Lee',
    rag_status: 'green',
    readiness_score: 8.0,
    open_gaps: 3,
    last_evaluated: '2026-04-28T10:20:00Z',
    validation_status: 'Validated',
  },
  {
    ci_id: 'SYS-007',
    system_name: 'Batch Record System',
    system_type: 'Electronic Batch Records',
    custodian: 'Claire Fontaine',
    owner: 'Raj Patel',
    rag_status: 'red',
    readiness_score: 3.6,
    open_gaps: 18,
    last_evaluated: '2026-04-24T13:10:00Z',
    validation_status: 'Validation Overdue',
  },
  {
    ci_id: 'SYS-008',
    system_name: 'Stability Monitor',
    system_type: 'Environmental Monitoring',
    custodian: 'Dr. Aiko Tanaka',
    owner: 'Nile Robinson',
    rag_status: 'green',
    readiness_score: 7.9,
    open_gaps: 4,
    last_evaluated: '2026-04-27T17:00:00Z',
    validation_status: 'Validated',
  },
]

export const MOCK_DASHBOARD = {
  systems: MOCK_SYSTEMS,
}

export const MOCK_GAPS = [
  {
    gap_id: 'GAP-001',
    ci_id: 'SYS-003',
    system_name: 'MES Gateway',
    description: 'Validation protocol VP-003 is missing an approved final signature.',
    severity: 'critical',
    status: 'open',
    control: '21 CFR Part 11 §11.10(e)',
    created_at: '2026-04-10T08:00:00Z',
    updated_at: '2026-04-28T09:00:00Z',
  },
  {
    gap_id: 'GAP-002',
    ci_id: 'SYS-007',
    system_name: 'Batch Record System',
    description: 'Audit trail review records missing for Q1 2026.',
    severity: 'critical',
    status: 'open',
    control: '21 CFR Part 11 §11.10(e)',
    created_at: '2026-04-12T10:30:00Z',
    updated_at: '2026-04-26T14:00:00Z',
  },
  {
    gap_id: 'GAP-003',
    ci_id: 'SYS-002',
    system_name: 'ELN Platform',
    description: 'Periodic review SOP-212 is 45 days overdue for re-approval.',
    severity: 'high',
    status: 'in_progress',
    control: 'EU Annex 11 §4.4',
    created_at: '2026-03-28T11:00:00Z',
    updated_at: '2026-04-20T16:00:00Z',
  },
  {
    gap_id: 'GAP-004',
    ci_id: 'SYS-005',
    system_name: 'Chromatography DS',
    description: 'User access roles not reviewed since system upgrade in Jan 2026.',
    severity: 'high',
    status: 'open',
    control: 'EU Annex 11 §12.1',
    created_at: '2026-04-01T09:15:00Z',
    updated_at: '2026-04-29T08:00:00Z',
  },
  {
    gap_id: 'GAP-005',
    ci_id: 'SYS-003',
    system_name: 'MES Gateway',
    description: 'Backup and restore procedure has not been tested in the last 12 months.',
    severity: 'high',
    status: 'open',
    control: 'EU Annex 11 §7.2',
    created_at: '2026-04-05T13:00:00Z',
    updated_at: '2026-04-25T10:30:00Z',
  },
  {
    gap_id: 'GAP-006',
    ci_id: 'SYS-001',
    system_name: 'LIMS Core',
    description: 'Change control CHG-1892 awaiting final QA sign-off.',
    severity: 'medium',
    status: 'in_progress',
    control: 'GAMP5 Category 4',
    created_at: '2026-04-15T14:00:00Z',
    updated_at: '2026-04-27T11:00:00Z',
  },
  {
    gap_id: 'GAP-007',
    ci_id: 'SYS-007',
    system_name: 'Batch Record System',
    description: 'Disaster recovery plan not updated after infrastructure migration.',
    severity: 'critical',
    status: 'open',
    control: 'EU Annex 11 §7.2',
    created_at: '2026-04-08T07:45:00Z',
    updated_at: '2026-04-28T15:00:00Z',
  },
  {
    gap_id: 'GAP-008',
    ci_id: 'SYS-005',
    system_name: 'Chromatography DS',
    description: 'IQ/OQ documentation not archived in the controlled document repository.',
    severity: 'medium',
    status: 'open',
    control: 'GAMP5 §5.4',
    created_at: '2026-04-18T10:00:00Z',
    updated_at: '2026-04-29T07:00:00Z',
  },
  {
    gap_id: 'GAP-009',
    ci_id: 'SYS-002',
    system_name: 'ELN Platform',
    description: 'Training records for 3 active users are missing completion certificates.',
    severity: 'medium',
    status: 'remediated',
    control: '21 CFR Part 211.68',
    created_at: '2026-03-20T09:00:00Z',
    updated_at: '2026-04-22T13:00:00Z',
  },
  {
    gap_id: 'GAP-010',
    ci_id: 'SYS-006',
    system_name: 'Regulatory Submissions',
    description: 'Electronic signature manifest log has gaps for submissions SR-441 to SR-445.',
    severity: 'low',
    status: 'accepted_exception',
    control: '21 CFR Part 11 §11.50',
    created_at: '2026-04-02T08:30:00Z',
    updated_at: '2026-04-19T16:00:00Z',
  },
  {
    gap_id: 'GAP-011',
    ci_id: 'SYS-008',
    system_name: 'Stability Monitor',
    description: 'Calibration certificate for humidity sensor CAL-0042 expires in 7 days.',
    severity: 'medium',
    status: 'open',
    control: 'USP <1058>',
    created_at: '2026-04-22T11:00:00Z',
    updated_at: '2026-04-29T09:00:00Z',
  },
  {
    gap_id: 'GAP-012',
    ci_id: 'SYS-004',
    system_name: 'QMS Suite',
    description: 'CAPA CAP-2204 root cause analysis section is incomplete.',
    severity: 'low',
    status: 'in_progress',
    control: 'ISO 9001:2015 §10.2',
    created_at: '2026-04-20T14:00:00Z',
    updated_at: '2026-04-28T12:00:00Z',
  },
]

export const MOCK_RUNS = [
  {
    run_id: 'RUN-20260429-001',
    trigger_type: 'scheduled',
    status: 'completed',
    started_at: '2026-04-29T06:00:00Z',
    completed_at: '2026-04-29T06:18:42Z',
    systems_processed: 8,
    systems_failed: 0,
  },
  {
    run_id: 'RUN-20260428-002',
    trigger_type: 'manual',
    status: 'completed',
    started_at: '2026-04-28T14:05:00Z',
    completed_at: '2026-04-28T14:22:10Z',
    systems_processed: 8,
    systems_failed: 1,
  },
  {
    run_id: 'RUN-20260427-001',
    trigger_type: 'scheduled',
    status: 'completed',
    started_at: '2026-04-27T06:00:00Z',
    completed_at: '2026-04-27T06:20:05Z',
    systems_processed: 8,
    systems_failed: 0,
  },
  {
    run_id: 'RUN-20260426-003',
    trigger_type: 'manual',
    status: 'failed',
    started_at: '2026-04-26T11:30:00Z',
    completed_at: '2026-04-26T11:31:22Z',
    systems_processed: 2,
    systems_failed: 2,
  },
  {
    run_id: 'RUN-20260425-001',
    trigger_type: 'scheduled',
    status: 'completed',
    started_at: '2026-04-25T06:00:00Z',
    completed_at: '2026-04-25T06:17:33Z',
    systems_processed: 8,
    systems_failed: 0,
  },
  {
    run_id: 'RUN-20260430-001',
    trigger_type: 'scheduled',
    status: 'scheduled',
    started_at: '2026-04-30T06:00:00Z',
    completed_at: null,
    systems_processed: null,
    systems_failed: null,
  },
]

export const MOCK_RUN_DETAILS = {
  'RUN-20260429-001': {
    run_id: 'RUN-20260429-001',
    system_statuses: MOCK_SYSTEMS.map(s => ({ ci_id: s.ci_id, system_name: s.system_name, status: 'completed' })),
    error_log: null,
  },
  'RUN-20260428-002': {
    run_id: 'RUN-20260428-002',
    system_statuses: MOCK_SYSTEMS.map((s, i) => ({
      ci_id: s.ci_id,
      system_name: s.system_name,
      status: i === 2 ? 'failed' : 'completed',
    })),
    error_log: 'SYS-003: Connection timeout after 30s — MES Gateway API unreachable.',
  },
  'RUN-20260427-001': {
    run_id: 'RUN-20260427-001',
    system_statuses: MOCK_SYSTEMS.map(s => ({ ci_id: s.ci_id, system_name: s.system_name, status: 'completed' })),
    error_log: null,
  },
  'RUN-20260426-003': {
    run_id: 'RUN-20260426-003',
    system_statuses: MOCK_SYSTEMS.slice(0, 2).map((s, i) => ({
      ci_id: s.ci_id,
      system_name: s.system_name,
      status: 'failed',
    })),
    error_log: 'Authentication failure: API key expired. Contact platform admin.',
  },
  'RUN-20260425-001': {
    run_id: 'RUN-20260425-001',
    system_statuses: MOCK_SYSTEMS.map(s => ({ ci_id: s.ci_id, system_name: s.system_name, status: 'completed' })),
    error_log: null,
  },
}

export const MOCK_NOTIFICATIONS = [
  {
    id: 'NOTIF-001',
    read: false,
    channel: 'in_app',
    type: 'critical',
    title: 'Critical Gap Detected — Batch Record System',
    message: 'GAP-007: Disaster recovery plan not updated after infrastructure migration. Immediate action required.',
    created_at: '2026-04-29T07:15:00Z',
  },
  {
    id: 'NOTIF-002',
    read: false,
    channel: 'email',
    type: 'alert',
    title: 'Inspection Readiness Score Dropped — MES Gateway',
    message: 'SYS-003 readiness score fell from 5.1 to 4.2. 14 open gaps remain unresolved.',
    created_at: '2026-04-29T06:20:00Z',
  },
  {
    id: 'NOTIF-003',
    read: false,
    channel: 'in_app',
    type: 'warning',
    title: 'Calibration Expiry Warning — Stability Monitor',
    message: 'Humidity sensor CAL-0042 calibration certificate expires in 7 days. Schedule renewal.',
    created_at: '2026-04-28T16:45:00Z',
  },
  {
    id: 'NOTIF-004',
    read: true,
    channel: 'in_app',
    type: 'info',
    title: 'Scheduled Run Completed Successfully',
    message: 'RUN-20260429-001 completed. All 8 systems processed with no failures.',
    created_at: '2026-04-29T06:19:00Z',
  },
  {
    id: 'NOTIF-005',
    read: true,
    channel: 'email',
    type: 'info',
    title: 'Gap Remediated — ELN Platform',
    message: 'GAP-009: Training records gap has been marked remediated by Priya Sharma.',
    created_at: '2026-04-22T13:05:00Z',
  },
  {
    id: 'NOTIF-006',
    read: false,
    channel: 'in_app',
    type: 'alert',
    title: 'Overdue Periodic Review — ELN Platform',
    message: 'SOP-212 periodic review is now 45 days overdue. Escalation triggered.',
    created_at: '2026-04-27T08:00:00Z',
  },
  {
    id: 'NOTIF-007',
    read: true,
    channel: 'email',
    type: 'info',
    title: 'New Gap Accepted as Exception — Regulatory Submissions',
    message: 'GAP-010 accepted as exception with documented justification by Susan Lee.',
    created_at: '2026-04-19T16:05:00Z',
  },
  {
    id: 'NOTIF-008',
    read: true,
    channel: 'in_app',
    type: 'warning',
    title: 'Manual Run Partially Failed',
    message: 'RUN-20260428-002: SYS-003 (MES Gateway) failed due to API timeout.',
    created_at: '2026-04-28T14:23:00Z',
  },
]

// Per-system artefacts, checklist, and score
export const MOCK_SYSTEM_ARTEFACTS = {
  'SYS-001': [
    { artefact_id: 'ART-001', artefact_name: 'Validation Protocol VP-001', category: 'Validation', doc_type: 'Protocol', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2026-03-15T10:00:00Z' },
    { artefact_id: 'ART-002', artefact_name: 'User Requirement Spec URS-001', category: 'Specification', doc_type: 'URS', approval_status: 'approved', source_system: 'SharePoint', url: '#', uploaded_at: '2026-02-20T09:00:00Z' },
    { artefact_id: 'ART-003', artefact_name: 'IQ Report IQ-001', category: 'Qualification', doc_type: 'IQ', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2026-01-10T11:00:00Z' },
    { artefact_id: 'ART-004', artefact_name: 'OQ Report OQ-001', category: 'Qualification', doc_type: 'OQ', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2026-01-12T13:00:00Z' },
    { artefact_id: 'ART-005', artefact_name: 'Periodic Review PR-2025-001', category: 'Review', doc_type: 'Periodic Review', approval_status: 'approved', source_system: 'SharePoint', url: '#', uploaded_at: '2025-12-01T09:00:00Z' },
  ],
  'SYS-002': [
    { artefact_id: 'ART-006', artefact_name: 'Validation Protocol VP-002', category: 'Validation', doc_type: 'Protocol', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2026-01-20T10:00:00Z' },
    { artefact_id: 'ART-007', artefact_name: 'SOP-212 Periodic Review', category: 'SOP', doc_type: 'SOP', approval_status: 'overdue', source_system: 'SharePoint', url: '#', uploaded_at: '2025-06-10T09:00:00Z' },
    { artefact_id: 'ART-008', artefact_name: 'OQ Report OQ-002', category: 'Qualification', doc_type: 'OQ', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2025-11-05T14:00:00Z' },
  ],
  'SYS-003': [
    { artefact_id: 'ART-009', artefact_name: 'Validation Protocol VP-003', category: 'Validation', doc_type: 'Protocol', approval_status: 'pending_signature', source_system: 'Veeva Vault', url: '#', uploaded_at: '2026-03-01T08:00:00Z' },
    { artefact_id: 'ART-010', artefact_name: 'Backup & Restore Procedure BRP-003', category: 'Procedure', doc_type: 'SOP', approval_status: 'expired', source_system: 'SharePoint', url: '#', uploaded_at: '2025-04-10T10:00:00Z' },
    { artefact_id: 'ART-011', artefact_name: 'Disaster Recovery Plan DRP-003', category: 'Plan', doc_type: 'DR Plan', approval_status: 'outdated', source_system: 'Confluence', url: '#', uploaded_at: '2024-11-20T09:00:00Z' },
  ],
  'SYS-004': [
    { artefact_id: 'ART-012', artefact_name: 'Validation Protocol VP-004', category: 'Validation', doc_type: 'Protocol', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2026-02-14T10:00:00Z' },
    { artefact_id: 'ART-013', artefact_name: 'IQ/OQ/PQ Package', category: 'Qualification', doc_type: 'IQ/OQ/PQ', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2026-01-30T12:00:00Z' },
    { artefact_id: 'ART-014', artefact_name: 'CAPA CAP-2204', category: 'CAPA', doc_type: 'CAPA', approval_status: 'in_review', source_system: 'TrackWise', url: '#', uploaded_at: '2026-04-18T09:00:00Z' },
    { artefact_id: 'ART-015', artefact_name: 'Change Control CHG-2044', category: 'Change Control', doc_type: 'Change Record', approval_status: 'approved', source_system: 'TrackWise', url: '#', uploaded_at: '2026-03-05T14:00:00Z' },
  ],
  'SYS-005': [
    { artefact_id: 'ART-016', artefact_name: 'Validation Protocol VP-005', category: 'Validation', doc_type: 'Protocol', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2025-09-10T10:00:00Z' },
    { artefact_id: 'ART-017', artefact_name: 'IQ Documentation IQ-005', category: 'Qualification', doc_type: 'IQ', approval_status: 'missing', source_system: '—', url: null, uploaded_at: null },
    { artefact_id: 'ART-018', artefact_name: 'User Access Review UAR-2026', category: 'Access Review', doc_type: 'Review', approval_status: 'overdue', source_system: 'SharePoint', url: '#', uploaded_at: '2025-12-01T09:00:00Z' },
  ],
  'SYS-006': [
    { artefact_id: 'ART-019', artefact_name: 'Validation Protocol VP-006', category: 'Validation', doc_type: 'Protocol', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2026-01-08T10:00:00Z' },
    { artefact_id: 'ART-020', artefact_name: 'Electronic Signature SOP ES-006', category: 'SOP', doc_type: 'SOP', approval_status: 'approved', source_system: 'SharePoint', url: '#', uploaded_at: '2026-02-01T11:00:00Z' },
    { artefact_id: 'ART-021', artefact_name: 'Periodic Review PR-2025-006', category: 'Review', doc_type: 'Periodic Review', approval_status: 'approved', source_system: 'SharePoint', url: '#', uploaded_at: '2025-11-15T09:00:00Z' },
  ],
  'SYS-007': [
    { artefact_id: 'ART-022', artefact_name: 'Validation Protocol VP-007', category: 'Validation', doc_type: 'Protocol', approval_status: 'revalidation_required', source_system: 'Veeva Vault', url: '#', uploaded_at: '2023-06-01T10:00:00Z' },
    { artefact_id: 'ART-023', artefact_name: 'Audit Trail Review Q1-2026', category: 'Audit', doc_type: 'Audit Report', approval_status: 'missing', source_system: '—', url: null, uploaded_at: null },
    { artefact_id: 'ART-024', artefact_name: 'Disaster Recovery Plan DRP-007', category: 'Plan', doc_type: 'DR Plan', approval_status: 'outdated', source_system: 'Confluence', url: '#', uploaded_at: '2024-08-10T09:00:00Z' },
  ],
  'SYS-008': [
    { artefact_id: 'ART-025', artefact_name: 'Validation Protocol VP-008', category: 'Validation', doc_type: 'Protocol', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2026-02-10T10:00:00Z' },
    { artefact_id: 'ART-026', artefact_name: 'Calibration Record CAL-0042', category: 'Calibration', doc_type: 'Calibration Cert.', approval_status: 'expiring_soon', source_system: 'LabWare', url: '#', uploaded_at: '2025-05-06T09:00:00Z' },
    { artefact_id: 'ART-027', artefact_name: 'Environmental Monitoring SOP EM-008', category: 'SOP', doc_type: 'SOP', approval_status: 'approved', source_system: 'SharePoint', url: '#', uploaded_at: '2025-10-20T11:00:00Z' },
    { artefact_id: 'ART-028', artefact_name: 'IQ/OQ Report IQ-OQ-008', category: 'Qualification', doc_type: 'IQ/OQ', approval_status: 'approved', source_system: 'Veeva Vault', url: '#', uploaded_at: '2025-12-15T14:00:00Z' },
  ],
}

export const MOCK_SYSTEM_CHECKLIST = {
  'SYS-001': [
    { item_name: 'Validation Protocol approved', category: 'Validation', status: 'met', notes: 'VP-001 signed and archived.' },
    { item_name: 'IQ/OQ/PQ completed', category: 'Qualification', status: 'met', notes: 'All qualification reports approved.' },
    { item_name: 'Periodic review current', category: 'Review', status: 'met', notes: 'PR-2025-001 completed Dec 2025.' },
    { item_name: 'Audit trail enabled & reviewed', category: 'Audit Trail', status: 'met', notes: 'Audit trail active and reviewed.' },
    { item_name: 'User access review', category: 'Access Control', status: 'incomplete', notes: 'UAR due within 14 days.' },
    { item_name: 'Change control closed', category: 'Change Management', status: 'incomplete', notes: 'CHG-1892 pending QA sign-off.' },
  ],
  'SYS-002': [
    { item_name: 'Validation Protocol approved', category: 'Validation', status: 'met', notes: 'VP-002 signed and archived.' },
    { item_name: 'IQ/OQ completed', category: 'Qualification', status: 'met', notes: 'OQ-002 approved Nov 2025.' },
    { item_name: 'Periodic review current', category: 'Review', status: 'missing', notes: 'SOP-212 overdue by 45 days.' },
    { item_name: 'Audit trail enabled', category: 'Audit Trail', status: 'met', notes: 'Audit trail active.' },
    { item_name: 'Training records complete', category: 'Training', status: 'incomplete', notes: '3 users missing certificates.' },
    { item_name: 'User access review', category: 'Access Control', status: 'incomplete', notes: 'Last review > 12 months ago.' },
    { item_name: 'Backup procedure tested', category: 'Business Continuity', status: 'met', notes: 'Tested Q4 2025.' },
  ],
  'SYS-003': [
    { item_name: 'Validation Protocol approved', category: 'Validation', status: 'missing', notes: 'VP-003 missing final QA signature.' },
    { item_name: 'IQ/OQ/PQ completed', category: 'Qualification', status: 'met', notes: 'Qualification reports on file.' },
    { item_name: 'Periodic review current', category: 'Review', status: 'met', notes: 'PR completed Jan 2026.' },
    { item_name: 'Audit trail enabled', category: 'Audit Trail', status: 'met', notes: 'Audit trail active.' },
    { item_name: 'Backup procedure tested', category: 'Business Continuity', status: 'missing', notes: 'Not tested in last 12 months.' },
    { item_name: 'Disaster recovery plan current', category: 'Business Continuity', status: 'missing', notes: 'DRP not updated post-migration.' },
    { item_name: 'User access review', category: 'Access Control', status: 'incomplete', notes: 'Review pending approval.' },
  ],
  'SYS-004': [
    { item_name: 'Validation Protocol approved', category: 'Validation', status: 'met', notes: 'VP-004 signed and archived.' },
    { item_name: 'IQ/OQ/PQ completed', category: 'Qualification', status: 'met', notes: 'Full package approved Jan 2026.' },
    { item_name: 'Periodic review current', category: 'Review', status: 'met', notes: 'PR completed Feb 2026.' },
    { item_name: 'Audit trail enabled & reviewed', category: 'Audit Trail', status: 'met', notes: 'Audit trail active and reviewed.' },
    { item_name: 'CAPA closed', category: 'CAPA', status: 'incomplete', notes: 'CAP-2204 root cause analysis incomplete.' },
    { item_name: 'User access review', category: 'Access Control', status: 'met', notes: 'UAR completed Mar 2026.' },
    { item_name: 'Backup procedure tested', category: 'Business Continuity', status: 'met', notes: 'Tested Q1 2026.' },
  ],
  'SYS-005': [
    { item_name: 'Validation Protocol approved', category: 'Validation', status: 'met', notes: 'VP-005 approved Sep 2025.' },
    { item_name: 'IQ documentation archived', category: 'Qualification', status: 'missing', notes: 'IQ-005 not in controlled repository.' },
    { item_name: 'User access review', category: 'Access Control', status: 'missing', notes: 'Not reviewed since Jan 2026 upgrade.' },
    { item_name: 'Periodic review current', category: 'Review', status: 'met', notes: 'PR completed Nov 2025.' },
    { item_name: 'Audit trail enabled', category: 'Audit Trail', status: 'met', notes: 'Audit trail active.' },
    { item_name: 'Backup procedure tested', category: 'Business Continuity', status: 'incomplete', notes: 'Test scheduled for May 2026.' },
  ],
  'SYS-006': [
    { item_name: 'Validation Protocol approved', category: 'Validation', status: 'met', notes: 'VP-006 signed and archived.' },
    { item_name: 'IQ/OQ/PQ completed', category: 'Qualification', status: 'met', notes: 'Qualification on file.' },
    { item_name: 'Periodic review current', category: 'Review', status: 'met', notes: 'PR-2025-006 approved Nov 2025.' },
    { item_name: 'Audit trail enabled', category: 'Audit Trail', status: 'met', notes: 'Audit trail active.' },
    { item_name: 'Electronic signature SOP current', category: 'Electronic Signatures', status: 'met', notes: 'ES-006 approved Feb 2026.' },
    { item_name: 'Signature manifest complete', category: 'Electronic Signatures', status: 'incomplete', notes: 'Gaps for SR-441 to SR-445.' },
  ],
  'SYS-007': [
    { item_name: 'Validation Protocol approved', category: 'Validation', status: 'missing', notes: 'Revalidation required — last validated 2023.' },
    { item_name: 'IQ/OQ/PQ completed', category: 'Qualification', status: 'met', notes: 'Historic qualification on file.' },
    { item_name: 'Audit trail review Q1-2026', category: 'Audit Trail', status: 'missing', notes: 'Review not completed.' },
    { item_name: 'Disaster recovery plan current', category: 'Business Continuity', status: 'missing', notes: 'DRP not updated post-migration.' },
    { item_name: 'User access review', category: 'Access Control', status: 'incomplete', notes: 'Review in progress.' },
    { item_name: 'Backup procedure tested', category: 'Business Continuity', status: 'incomplete', notes: 'Overdue by 2 months.' },
    { item_name: 'Training records complete', category: 'Training', status: 'met', notes: 'All active users trained.' },
  ],
  'SYS-008': [
    { item_name: 'Validation Protocol approved', category: 'Validation', status: 'met', notes: 'VP-008 approved Feb 2026.' },
    { item_name: 'IQ/OQ completed', category: 'Qualification', status: 'met', notes: 'IQ-OQ-008 approved Dec 2025.' },
    { item_name: 'Periodic review current', category: 'Review', status: 'met', notes: 'PR completed Oct 2025.' },
    { item_name: 'Calibration current', category: 'Calibration', status: 'incomplete', notes: 'CAL-0042 expires in 7 days.' },
    { item_name: 'Audit trail enabled & reviewed', category: 'Audit Trail', status: 'met', notes: 'Audit trail active and reviewed.' },
    { item_name: 'User access review', category: 'Access Control', status: 'met', notes: 'UAR completed Jan 2026.' },
    { item_name: 'Backup procedure tested', category: 'Business Continuity', status: 'met', notes: 'Tested Q1 2026.' },
  ],
}

export const MOCK_SYSTEM_SCORES = {
  'SYS-001': {
    score: 8.7,
    rag_status: 'green',
    coverage_pct: 91,
    explainability: { documentation: 0.92, audit_trail: 0.95, validation: 0.88, training: 0.82, access_control: 0.84 },
  },
  'SYS-002': {
    score: 6.1,
    rag_status: 'amber',
    coverage_pct: 66,
    explainability: { documentation: 0.72, audit_trail: 0.80, validation: 0.65, training: 0.50, access_control: 0.55 },
  },
  'SYS-003': {
    score: 4.2,
    rag_status: 'red',
    coverage_pct: 48,
    explainability: { documentation: 0.40, audit_trail: 0.70, validation: 0.35, training: 0.60, access_control: 0.42 },
  },
  'SYS-004': {
    score: 9.1,
    rag_status: 'green',
    coverage_pct: 95,
    explainability: { documentation: 0.96, audit_trail: 0.98, validation: 0.94, training: 0.90, access_control: 0.92 },
  },
  'SYS-005': {
    score: 5.8,
    rag_status: 'amber',
    coverage_pct: 60,
    explainability: { documentation: 0.55, audit_trail: 0.75, validation: 0.62, training: 0.68, access_control: 0.40 },
  },
  'SYS-006': {
    score: 8.0,
    rag_status: 'green',
    coverage_pct: 86,
    explainability: { documentation: 0.88, audit_trail: 0.85, validation: 0.82, training: 0.78, access_control: 0.80 },
  },
  'SYS-007': {
    score: 3.6,
    rag_status: 'red',
    coverage_pct: 38,
    explainability: { documentation: 0.30, audit_trail: 0.50, validation: 0.25, training: 0.55, access_control: 0.45 },
  },
  'SYS-008': {
    score: 7.9,
    rag_status: 'green',
    coverage_pct: 84,
    explainability: { documentation: 0.85, audit_trail: 0.90, validation: 0.82, training: 0.78, access_control: 0.80 },
  },
}
